# Generated by Django 5.2.3 on 2025-07-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='year',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='keam_app.year'),
            preserve_default=False,
        ),
    ]
