# Generated by Django 5.2.3 on 2025-07-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keam_app', '0002_year_board_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='keam_app.year'),
        ),
    ]
