# Generated by Django 5.2.3 on 2025-07-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keam_app', '0003_alter_board_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['year', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subjectstat',
            options={'ordering': ['board__year', 'board__name', 'subject'], 'verbose_name': 'Subject Statistics', 'verbose_name_plural': 'Subject Statistics'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-value'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AddField(
            model_name='board',
            name='max_mark',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subjectstat',
            name='max_mark',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keam_app.year'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('name', 'year')},
        ),
    ]
